name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize
        uses: ./.github/actions/init
      - run: yarn build

  codecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize
        uses: ./.github/actions/init
      - run: yarn codecheck

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize
        uses: ./.github/actions/init
      - run: yarn test:ci

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize
        uses: ./.github/actions/init
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: yarn start
